import { TaskDto } from './task-api.typings';

export const TASKS: TaskDto[] = [
  {
    id: 1,
    name: 'Task 1',
    description: 'Description for Task 1',
    completed: false,
    startDate: new Date('2023-01-01'),
    endDate: new Date('2023-01-05'),
  },
  {
    id: 2,
    name: 'Task 2',
    description: 'Description for Task 2',
    completed: true,
    startDate: new Date('2023-01-06'),
    endDate: new Date('2023-01-10'),
  },
  {
    id: 3,
    name: 'Task 3',
    description: 'Description for Task 3',
    completed: false,
  },
  {
    id: 4,
    name: 'Task 4',
    description: 'Description for Task 4',
    completed: true,
    startDate: new Date('2023-02-01'),
    endDate: new Date('2023-02-07'),
  },
  {
    id: 5,
    name: 'Task 5',
    description: 'Description for Task 5',
    completed: false,
    startDate: new Date('2023-02-10'),
    endDate: new Date('2023-02-15'),
  },
  {
    id: 6,
    name: 'Task 6',
    description: 'Description for Task 6',
    completed: false,
    startDate: new Date('2023-03-01'),
    endDate: new Date('2023-03-02'),
  },
  // {
  //   id: 7,
  //   name: 'Task 7',
  //   completed: true,
  // },
  // {
  //   id: 8,
  //   name: 'Task 8',
  //   description: 'Description for Task 8',
  //   completed: false,
  // },
  // {
  //   id: 9,
  //   name: 'Task 9',
  //   description: 'Description for Task 9',
  //   completed: true,
  //   startDate: new Date('2023-04-01'),
  // },
  // {
  //   id: 10,
  //   name: 'Task 10',
  //   description: 'Description for Task 10',
  //   completed: false,
  // },
  // {
  //   id: 11,
  //   name: 'Task 11',
  //   description: 'Description for Task 11',
  //   completed: false,
  //   startDate: new Date('2023-05-01'),
  //   endDate: new Date('2023-05-10'),
  // },
  // {
  //   id: 12,
  //   name: 'Task 12',
  //   description: 'Description for Task 12',
  //   completed: true,
  //   startDate: new Date('2023-05-11'),
  //   endDate: new Date('2023-05-15'),
  // },
  // {
  //   id: 13,
  //   name: 'Task 13',
  //   completed: false,
  // },
  // {
  //   id: 14,
  //   name: 'Task 14',
  //   description: 'Description for Task 14',
  //   completed: true,
  //   startDate: new Date('2023-06-01'),
  // },
  // {
  //   id: 15,
  //   name: 'Task 15',
  //   description: 'Description for Task 15',
  //   completed: false,
  //   endDate: new Date('2023-06-05'),
  // },
  // {
  //   id: 16,
  //   name: 'Task 16',
  //   completed: true,
  // },
  // {
  //   id: 17,
  //   name: 'Task 17',
  //   description: 'Description for Task 17',
  //   completed: false,
  // },
  // {
  //   id: 18,
  //   name: 'Task 18',
  //   description: 'Description for Task 18',
  //   completed: true,
  //   startDate: new Date('2023-07-01'),
  //   endDate: new Date('2023-07-10'),
  // },
  // {
  //   id: 19,
  //   name: 'Task 19',
  //   description: 'Description for Task 19',
  //   completed: false,
  // },
  // {
  //   id: 20,
  //   name: 'Task 20',
  //   description: 'Description for Task 20',
  //   completed: true,
  //   startDate: new Date('2023-08-01'),
  // },
  // {
  //   id: 21,
  //   name: 'Task 21',
  //   completed: false,
  // },
  // {
  //   id: 22,
  //   name: 'Task 22',
  //   description: 'Description for Task 22',
  //   completed: true,
  //   startDate: new Date('2023-09-01'),
  //   endDate: new Date('2023-09-05'),
  // },
  // {
  //   id: 23,
  //   name: 'Task 23',
  //   description: 'Description for Task 23',
  //   completed: false,
  //   endDate: new Date('2023-09-10'),
  // },
  // {
  //   id: 24,
  //   name: 'Task 24',
  //   description: 'Description for Task 24',
  //   completed: true,
  // },
  // {
  //   id: 25,
  //   name: 'Task 25',
  //   description: 'Description for Task 25',
  //   completed: false,
  // },
];
